version: "3.9"

services:
  api:
    build: .
    container_name: flask_blacklist_api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/appdb
      DB_HOST: db
      DB_PORT: "5432"
      JWT_SECRET_KEY: "clave-super-secreta"
      STATIC_JWT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoic3RhdGljLXVzZXIiLCJyb2xlIjoiYWRtaW4ifQ.6bUHdYJk1cRnn-SVZEXAMPLEpR0fZ2mJb_YWbl8pW1lM
      FLASK_ENV: production
      # New Relic Configuration (opcional para desarrollo local)
      NEW_RELIC_LICENSE_KEY: "2EDE0C817854163612AA23FB3EC9A412CD3C1F31D7D4C22066FA11AB057C1C06"
      NEW_RELIC_APP_NAME: "popcorn-app-dev"
      NEW_RELIC_LOG: "stdout"
      NEW_RELIC_LOG_LEVEL: "info"
      NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: "true"

  db:
    image: postgres:16
    container_name: postgres_appdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d appdb -h 127.0.0.1 -p 5432"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
